spring:
  datasource:
    url: jdbc:mysql://localhost:3307/cafeminsu?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME:cafeminsu}
    password: ${DB_PASSWORD:cafeminsu}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      # password: ${REDIS_PASSWORD:}   # 로컬은 비밀번호 없음

  jpa:
    show-sql: true
